#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
hour=0
while [ $hour -le 12 ]
do
    minute=0
    while [ $minute -le 59 ]
    do
        echo "Hour: $hour"
        echo "Minute: $minute"
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done
